const translations = {
    "en": {
        "nav-services": "Services",
        "nav-process": "Process",
        "nav-gallery": "Gallery",
        "nav-faq": "FAQ",
        "nav-contact": "Contact",
        "hero-title": "Jacksonville Spray Foam Insulation<br><span style='color: var(--color-mustard);'>Built for Florida Heat & Humidity</span>",
        "hero-subtitle": "Seal your home against Florida heat, humidity, and high energy bills with clean, professional spray foam insulation.",
        "hero-btn-estimate": "Get a Free Estimate",
        "hero-btn-call": "Call Now",
        "hero-btn-whatsapp": "Text Us on WhatsApp",
        "trust-local": "Local Jacksonville Service",
        "trust-estimates": "Free Estimates",
        "trust-bilingual": "English & Spanish",
        "trust-clean": "Clean Installation",
        "trust-honest": "Honest Recommendations",
        "services-title": "Expert Insulation Services<br><span style='color: var(--color-mustard);'>Tailored for You</span>",
        "service-attic-title": "Attic Spray Foam Insulation",
        "service-attic-desc": "Help reduce heat transfer, improve comfort, and support better AC performance.",
        "service-garage-title": "Garage & Bonus Room Insulation",
        "service-garage-desc": "Turn hot, uncomfortable spaces into more usable areas. Converting a garage or carport? We can help control heat before drywall finishes.",
        "service-crawl-title": "Crawl Space Insulation",
        "service-crawl-desc": "Help control moisture, air leaks, and humidity from below your home.",
        "service-metal-title": "Metal Building Spray Foam",
        "service-metal-desc": "Improve temperature control and reduce condensation in workshops, warehouses, and storage buildings.",
        "service-new-title": "New Construction & Remodels",
        "service-new-desc": "Get proper air sealing from the beginning of your project.",
        "service-commercial-title": "Small Commercial Spray Foam",
        "service-commercial-desc": "Energy-efficient insulation for offices, shops, warehouses, and buildouts.",
        "climate-title": "Made for <span>Jacksonville Weather</span>",
        "climate-desc": "Jacksonville homes face intense heat, high humidity, heavy rain, and moisture challenges throughout the year. Spray foam insulation helps create an air seal that can reduce drafts, improve comfort, and help your HVAC system work more efficiently.",
        "climate-serving": "Proudly serving:",
        "climate-protect": "Protect Your Space",
        "climate-protect-desc": "From Florida's extreme humidity and heat.",
        "why-title": "Why Choose <span>A&A Spray Foam?</span>",
        "why-1": "Clear Communication: We explain the process before we start.",
        "why-2": "Honest Recommendations: We do not sell you something your property does not need.",
        "why-3": "Clean Work: We respect your home and prepare the area before installation.",
        "why-4": "Local Service: We serve Jacksonville and Northeast Florida with direct, personal attention.",
        "why-5": "English & Spanish Support: We make sure you understand your options clearly.",
        "why-bilingual": "Bilingual Experts",
        "why-bilingual-desc": "We speak your language. Hablamos Español.",
        "process-title": "Our Simple <span>4-Step Process</span>",
        "step-1-title": "Request Your Free Estimate",
        "step-1-desc": "Call us, text us, or send your project details.",
        "step-2-title": "Project Review",
        "step-2-desc": "We look at the area and understand your goals.",
        "step-3-title": "Foam Recommendation",
        "step-3-desc": "We explain whether open-cell or closed-cell makes more sense.",
        "step-4-title": "Installation Day",
        "step-4-desc": "We prepare, spray, clean, and review the job with you.",
        "process-btn": "Start Step 1: Text Us Now",
        "edu-compare-title": "Open-Cell vs Closed-Cell",
        "edu-open-title": "Open-Cell Spray Foam",
        "edu-open-desc": "Best for interior walls, attics, and sound control.",
        "edu-open-benefit": "More affordable and great for air sealing.",
        "edu-closed-title": "Closed-Cell Spray Foam",
        "edu-closed-desc": "Best for metal buildings, crawl spaces, moisture-prone areas.",
        "edu-closed-benefit": "Higher R-value, moisture resistance, and added strength.",
        "edu-compare-note": "Not sure which one you need? We will explain the difference during your free estimate.",
        "edu-pricing-title": "How is Pricing Determined?",
        "edu-pricing-desc": "We don't believe in hidden fees. The cost of your project depends on several factors:",
        "price-factor-1": "Size of the area (Square footage).",
        "price-factor-2": "Foam type: open-cell or closed-cell.",
        "price-factor-3": "Required thickness (R-value).",
        "price-factor-4": "Access difficulty & Ventilation.",
        "price-factor-5": "Existing insulation removal.",
        "price-factor-6": "New construction versus retrofit.",
        "edu-ready-title": "Not ready for an appointment?",
        "edu-ready-desc": "Send pictures of your attic, garage, crawl space, or metal building and we will guide you on what may be needed.",
        "edu-ready-btn": "Send Us Photos First",
        "safety-title": "Safety-Focused <span>Installation</span>",
        "safety-desc": "We follow proper preparation, ventilation, and cleanup practices so every project is handled carefully from start to finish.",
        "safety-1-title": "Preparation",
        "safety-1-desc": "Thorough work area preparation to protect your property.",
        "safety-2-title": "Ventilation",
        "safety-2-desc": "Strict ventilation awareness and manufacturer guidelines.",
        "safety-3-title": "Protection",
        "safety-3-desc": "Proper PPE (Personal Protective Equipment) for all installers.",
        "safety-4-title": "Clean Jobsite",
        "safety-4-desc": "We leave the site clean and conduct a final review with you.",
        "gallery-title": "Real Work. <span>Real Results.</span>",
        "gallery-btn": "Book Your Project",
        "faq-title": "Frequently Asked <span>Questions</span>",
        "contact-title": "Ready to Insulate <span>Your Property?</span>",
        "contact-desc": "Get in touch with A&A Spray Foam Inc. today for a free consultation and estimate.",
        "contact-info-title": "Contact Information",
        "contact-info-desc": "Serving Jacksonville, FL and surrounding areas.",
        "contact-area": "Service Area",
        "contact-phone": "Phone",
        "contact-email": "Email",
        "contact-whatsapp": "Chat on WhatsApp",
        "contact-sms": "Send SMS",
        "form-title": "Request Free Estimate",
        "form-desc": "Or send us photos of your project to get guided advice.",
        "label-name": "Name",
        "label-phone": "Phone",
        "label-email": "Email",
        "label-type": "Project Type",
        "label-sqft": "Approx. Sq Ft",
        "label-city": "City / Area",
        "label-message": "Message",
        "label-photos": "Upload Photos (Optional)",
        "form-btn": "Send Request",
        "faq-q-1": "Is spray foam good for Jacksonville homes?",
        "faq-a-1": "Yes. Spray foam can help reduce air leaks, improve comfort, and support moisture control, which is important in Florida’s hot and humid climate.",
        "faq-q-2": "How much does it cost?",
        "faq-a-2": "The cost varies based on square footage and foam type. We provide free estimates to give you an accurate price for your project.",
        "faq-q-3": "Do you speak Spanish?",
        "faq-a-3": "Yes. We communicate in English and Spanish.",
        "gallery-before": "Before",
        "gallery-after": "After"
    },
    "es": {
        "nav-services": "Servicios",
        "nav-process": "Proceso",
        "nav-gallery": "Galería",
        "nav-faq": "Preguntas",
        "nav-contact": "Contacto",
        "hero-title": "Aislamiento de Espuma en Jacksonville<br><span style='color: var(--color-mustard);'>Para el Calor y Humedad de Florida</span>",
        "hero-subtitle": "Proteja su hogar contra el calor de Florida, la humedad y las altas facturas de energía con aislamiento de espuma profesional y limpio.",
        "hero-btn-estimate": "Obtener Presupuesto Gratis",
        "hero-btn-call": "Llamar Ahora",
        "hero-btn-whatsapp": "Escríbenos por WhatsApp",
        "trust-local": "Servicio Local en Jacksonville",
        "trust-estimates": "Presupuestos Gratis",
        "trust-bilingual": "Inglés y Español",
        "trust-clean": "Instalación Limpia",
        "trust-honest": "Recomendaciones Honestas",
        "services-title": "Servicios Expertos de Aislamiento<br><span style='color: var(--color-mustard);'>Diseñados para Usted</span>",
        "service-attic-title": "Aislamiento de Áticos",
        "service-attic-desc": "Ayuda a reducir la transferencia de calor, mejora el confort y optimiza el rendimiento del aire acondicionado.",
        "service-garage-title": "Aislamiento de Garajes y Habitaciones Extra",
        "service-garage-desc": "Convierta espacios calurosos e incómodos en áreas útiles. ¿Va a convertir un garaje? Podemos ayudar a controlar el calor antes de los acabados.",
        "service-crawl-title": "Aislamiento de Espacios Bajos (Crawl Space)",
        "service-crawl-desc": "Ayuda a controlar la humedad y las filtraciones de aire desde debajo de su hogar.",
        "service-metal-title": "Espuma para Edificios Metálicos",
        "service-metal-desc": "Mejora el control de temperatura y reduce la condensación en talleres, almacenes y depósitos.",
        "service-new-title": "Construcción Nueva y Remodelaciones",
        "service-new-desc": "Obtenga un sellado de aire adecuado desde el principio de su proyecto.",
        "service-commercial-title": "Espuma Comercial Pequeña",
        "service-commercial-desc": "Aislamiento eficiente para oficinas, tiendas, almacenes y remodelaciones comerciales.",
        "climate-title": "Hecho para el <span>Clima de Jacksonville</span>",
        "climate-desc": "Las casas en Jacksonville enfrentan calor intenso, alta humedad y lluvias constantes durante todo el año. El aislamiento de espuma crea un sello de aire que reduce las corrientes, mejora el confort y ayuda a su sistema de aire acondicionado a trabajar eficientemente.",
        "climate-serving": "Sirviendo orgullosamente a:",
        "climate-protect": "Proteja su Espacio",
        "climate-protect-desc": "Del calor y la humedad extrema de Florida.",
        "why-title": "¿Por qué elegir <span>A&A Spray Foam?</span>",
        "why-1": "Comunicación Clara: Explicamos el proceso antes de comenzar.",
        "why-2": "Recomendaciones Honestas: No le vendemos algo que su propiedad no necesite.",
        "why-3": "Trabajo Limpio: Respetamos su hogar y preparamos el área antes de la instalación.",
        "why-4": "Servicio Local: Atendemos Jacksonville y el noreste de Florida con atención personal directa.",
        "why-5": "Apoyo en Inglés y Español: Nos aseguramos de que entienda sus opciones claramente.",
        "why-bilingual": "Expertos Bilingües",
        "why-bilingual-desc": "Hablamos su idioma. English & Spanish.",
        "process-title": "Nuestro Proceso <span>Simple de 4 Pasos</span>",
        "step-1-title": "Solicite su Presupuesto Gratis",
        "step-1-desc": "Llámenos, envíenos un texto o los detalles de su proyecto.",
        "step-2-title": "Revisión del Proyecto",
        "step-2-desc": "Miramos el área y entendemos sus objetivos.",
        "step-3-title": "Recomendación de Espuma",
        "step-3-desc": "Explicamos si tiene más sentido la celda abierta o cerrada.",
        "step-4-title": "Día de Instalación",
        "step-4-desc": "Preparamos, aplicamos, limpiamos y revisamos el trabajo con usted.",
        "process-btn": "Iniciar Paso 1: Escríbenos Ahora",
        "edu-compare-title": "Celda Abierta vs Celda Cerrada",
        "edu-open-title": "Espuma de Celda Abierta",
        "edu-open-desc": "Ideal para paredes interiores, áticos y control de sonido.",
        "edu-open-benefit": "Más económica y excelente para sellado de aire.",
        "edu-closed-title": "Espuma de Celda Cerrada",
        "edu-closed-desc": "Ideal para edificios metálicos, espacios bajos y áreas propensas a la humedad.",
        "edu-closed-benefit": "Mayor valor R, resistencia a la humedad y fuerza estructural.",
        "edu-compare-note": "¿No está seguro de cuál necesita? Le explicaremos la diferencia durante su presupuesto gratuito.",
        "edu-pricing-title": "¿Cómo se determina el precio?",
        "edu-pricing-desc": "No creemos en tarifas ocultas. El costo de su proyecto depende de varios factores:",
        "price-factor-1": "Tamaño del área (Pies cuadrados).",
        "price-factor-2": "Tipo de espuma: celda abierta o cerrada.",
        "price-factor-3": "Espesor requerido (Valor R).",
        "price-factor-4": "Dificultad de acceso y ventilación.",
        "price-factor-5": "Eliminación de aislamiento existente.",
        "price-factor-6": "Construcción nueva vs. remodelación.",
        "edu-ready-title": "¿No está listo para una cita?",
        "edu-ready-desc": "Envíenos fotos de su ático, garaje o edificio y le guiaremos sobre lo que puede ser necesario.",
        "edu-ready-btn": "Enviarnos Fotos Primero",
        "safety-title": "Instalación Enfocada en <span>la Seguridad</span>",
        "safety-desc": "Seguimos prácticas adecuadas de preparación, ventilación y limpieza para que cada proyecto se maneje con cuidado de principio a fin.",
        "safety-1-title": "Preparación",
        "safety-1-desc": "Preparación minuciosa del área de trabajo para proteger su propiedad.",
        "safety-2-title": "Ventilación",
        "safety-2-desc": "Conciencia estricta de la ventilación y pautas del fabricante.",
        "safety-3-title": "Protección",
        "safety-3-desc": "EPP (Equipo de Protección Personal) adecuado para todos los instaladores.",
        "safety-4-title": "Limpieza",
        "safety-4-desc": "Dejamos el sitio limpio y realizamos una revisión final con usted.",
        "gallery-title": "Trabajo Real. <span>Resultados Reales.</span>",
        "gallery-btn": "Reservar Proyecto",
        "faq-title": "Preguntas <span>Frecuentes</span>",
        "contact-title": "¿Listo para aislar <span>su propiedad?</span>",
        "contact-desc": "Póngase en contacto con A&A Spray Foam Inc. hoy para una consulta y presupuesto gratuito.",
        "contact-info-title": "Información de Contacto",
        "contact-info-desc": "Sirviendo a Jacksonville, FL y áreas circundantes.",
        "contact-area": "Área de Servicio",
        "contact-phone": "Teléfono",
        "contact-email": "Correo Electrónico",
        "contact-whatsapp": "Chat por WhatsApp",
        "contact-sms": "Enviar SMS",
        "form-title": "Solicitar Presupuesto Gratis",
        "form-desc": "O envíenos fotos de su proyecto para recibir asesoramiento guiado.",
        "label-name": "Nombre",
        "label-phone": "Teléfono",
        "label-email": "Correo",
        "label-type": "Tipo de Proyecto",
        "label-sqft": "Pies Cuadrados Aprox.",
        "label-city": "Ciudad / Área",
        "label-message": "Mensaje",
        "label-photos": "Subir Fotos (Opcional)",
        "form-btn": "Enviar Solicitud",
        "faq-q-1": "¿Es buena la espuma para las casas de Jacksonville?",
        "faq-a-1": "Sí. La espuma ayuda a reducir las filtraciones de aire, mejora el confort y ayuda al control de humedad, lo cual es vital en el clima cálido de Florida.",
        "faq-q-2": "¿Cuánto cuesta?",
        "faq-a-2": "El costo varía según los pies cuadrados y el tipo de espuma. Ofrecemos presupuestos gratuitos para darte un precio exacto.",
        "faq-q-3": "¿Hablan español?",
        "faq-a-3": "Sí. Nos comunicamos tanto en inglés como en español.",
        "gallery-before": "Antes",
        "gallery-after": "Después"
    }
};
